### ISSUE TITLE
[Enhancement Request] Add an inventory page

### ISSUE THREAD

**Issue by Mephi-Dross** [iansjk/arknights-tools#19]
**Issue:**
As someone who regularly uses the tool, I'd love a better way to manage the different items in my inventory. The current way only lets you add items that are relevant to the current goal, which makes sense, but it is a bit annoying to constantly having to toggle the crafting state just to edit some of the lesser materials.

**Proposed solution:**
- Adding an extra page which contains all of the items in the inventory
- Possibly copy the crafting functionality
- Maybe export/import of a simple JSON string

---
I hope this is the right spot to ask for this kinda thing and I apologize if it isn't.

**Comment by iansjk** [comment]
I think this is an intended feature, though I don't have a public roadmap for the site. I vaguely remember experimenting with adding a tab for the entire Depot as opposed to just items required for current goals.

I'll look into this once the Młynar update is out–that ended up causing some complications because of character search not returning results for `Mlynar` + Aceship splitting off assets into a separate repo.

**Comment by iansjk** [comment]
Hi, just wanted to let you know that @neeia contributed PR #23 which implements this. You can go to settings, then check "Show inactive materials" to display all items at once, including those you don't immediately need:
![image](https://user-images.githubusercontent.com/1508774/199877455-232c34a6-fc92-4bca-b00a-7b70beea22ae.png)
