### ISSUE TITLE
Feature Request: Use github action for automated site updates

### ISSUE THREAD

**Issue by zhaoweny** [iansjk/arknights-tools#21]
Hi,

Hyperglyph releases yet another content updates (IS3) on 2022/09/26 to CN servers. Manual updates always takes time and effort on your end. I'm proposing to utilize GitHub dependabot for automated content repository update.

I've setup a fork that demos this approach [link](https://github.com/zhaoweny/arknights-tools). You can see that dependabot has opened a PR for submodule update. Combining dependabot and github action, arknights-tools can get fresh content update with a few clicks.

May I proceed to setup additional GitHub Action for auto uploading images, and auto update `data/` folder? I have registered a test project on Cloudinary for this demo, and maybe you can fill the actual keys later in your repo.

**Comment by iansjk** [comment]
Ah, thanks for writing. I just looked at your fork, and I see you've figured out the steps in the repo...

The reason why Arknights-Images is not a submodule is because it's far too large, and Netlify/Vercel/etc. will clone all submodules on each build. (Last I checked–which was quite a while ago–there wasn't a way to customize which submodules got cloned.) Before Aceship split off just the images into their own repo, it was actually large enough to fail the build because it wouldn't clone in time. I imagine it might not be *so* bad now that e.g. audio assets are held elsewhere, but I'm guessing it would still take a while. Did you try uploading your fork to a webhost (Cloudflare Pages, Vercel, etc.) to see if it built as expected?

At one point I had a fork of the Aceship repo from which I removed almost everything except just the images I actually used on the site, but then it's a problem of maintaining the fork automatically rather than this repo.

I certainly like the idea of automatically updating the site via a PR. Note that there are occasionally some additional issues that require manual changes–most recently the example of Młynar, which posed some issues for the operator search autocomplete (most people would presumably search for `Mlynar`, without the L-bar character, and I had to make the operator search match that as well).

**Comment by zhaoweny** [comment]
> Did you try uploading your fork to a webhost

not yet, I guess it's on my project to-do list now.

I discovered that I cloned the wrong repo for Arknights-Images :( - fixing it now. Now there are 2 repos lives under `scripts`, would you mind that I do a little renaming for `ArknightsGameData` ?
* `ArknightsGameData` will become just `GameData`
* new `Arknight-Images` will be named as `Images`

I have the necessary bits to setup on Cloudflare pages. I guess I can upload the images, then deploy it on Cloudflare Pages.

**Comment by iansjk** [comment]
Yeah, it would be fine to rename the submodules. Again, I *believe* the blocker for me last time when I attempted some automation was that including the Aceship asset repo (of which the images portion is now called `Arknight-Images`) was too heavy to successfully build the site. But I would be pleasantly surprised if it worked out.

**Comment by zhaoweny** [comment]
Good news: It clones just fine on Cloudflare Pages. Check this piece of build log:

```
13:10:33.557 | Cloning repository...
13:10:34.982 | From https://github.com/zhaoweny/arknights-tools
13:10:34.982 | * branch            8f6ff940f22f72232fac899d21d0153c3500b099 -> FETCH_HEAD
13:10:34.982 |  
13:10:35.081 | HEAD is now at 8f6ff94 update scripts for 'GameData' rename
13:10:35.082 |  
13:13:46.649 | Submodule 'scripts/ArknightsGameData' (https://github.com/Kengxxiao/ArknightsGameData.git) registered for path 'scripts/GameData'
13:13:46.650 | Submodule 'ArknightsImages' (https://github.com/Aceship/Arknight-Images) registered for path 'scripts/Images'
13:13:46.650 | Cloning into '/opt/buildhome/clone/scripts/GameData'...
13:13:46.651 | Cloning into '/opt/buildhome/clone/scripts/Images'...
13:13:46.651 | Submodule path 'scripts/GameData': checked out 'b4ba39be397a3f68523b2e984046dc656d8c2d35'
13:13:46.651 | Submodule path 'scripts/Images': checked out '937b02253931780aeb41dd914de9b2aa031b7fe3'
13:13:46.652 |  
13:13:46.700 | Success: Finished cloning repository files
```
This means (with modern build servers, modern server networking) a few GiB sized repo is not a big deal anymore.

**Comment by iansjk** [comment]
Excellent! Well, that's great news, and simplifies things nicely. If you want to open a PR I can set up the repo so that it passes Cloudinary secrets to the GH action.

**Comment by zhaoweny** [comment]
I'll continue with Cloudflare Pages, but drive the build & deploy process with GitHub Action instead. This way I can create a all-in-one build script that does all the necessary bits for content update. (Maybe we can check PR names and skips running `scripts/all.mjs` if the PR is not about submodule update.)

**Comment by zhaoweny** [comment]
Now I have filled all the necessary bits to run a deploy to Cloudflare Pages ...

**Comment by zhaoweny** [comment]
The game data repo is so heavy, that I have to abandon this idea. Here is my summary of this experment:

* Though GiB-sized repo is not a issue on Cloudflare, it certainly is for me (with a slower connection)
* My idea of using dependabot does not work, because MRs can't use repository's secret, and will fail to build.
